[build]
command = """
pip install -r requirements.txt
python -m pip install --upgrade pip
python -m pip install gunicorn
"""
publish = "."
functions = "netlify/functions"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["express"]

[build.environment]
NODE_VERSION = "18"
PYTHON_VERSION = "3.10"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https:; img-src 'self' data: https:; connect-src 'self' https:;"