name: Branch Protection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-build:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest tests/

  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run linting
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  protect-main:
    needs: [verify-build, lint-check]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate no direct pushes to main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "⚠️ Direct pushes to main branch are not allowed"
          echo "Please create a pull request instead"
          exit 1

      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pytest

      - name: Require review
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request
            if (!pr.requested_reviewers || pr.requested_reviewers.length === 0) {
              core.setFailed('Pull request requires at least one reviewer')
            }
