name: Branch Protection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  protect-main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate no direct pushes to main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "⚠️ Direct pushes to main branch are not allowed"
          echo "Please create a pull request instead"
          exit 1

      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pytest

      - name: Require review
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request
            if (!pr.requested_reviewers || pr.requested_reviewers.length === 0) {
              core.setFailed('Pull request requires at least one reviewer')
            }
